"""
Define EpisodeStep (transition), Trajectory (sequence of EpisodeStep),
TrajectoryGroup (batch of Trajectory)
"""

from typing import Any

from pydantic import BaseModel

from .utils.returns import compute_returns_with_last_value


class EpisodeStep(BaseModel):
    """
    Single episode step, i.e., a transition between two states
    -> Note that tools is optional, but should be saved if available
    """

    state: list[dict[str, Any]]
    action: dict[str, Any]
    next_obs: list[dict[str, Any]]

    state_action_tokens: list[int] | None
    state_len: int
    # old_logprobs: list[float] | None
    # temperature: float | None

    reward: float
    done: bool
    truncated: bool
    timestep: int
    try_step: int

    batch_id: int
    unique_data_sample_id: int
    generation_id: int
    split: str

    # We won't need these attributes for inference-only
    old_logprobs: list[float] | None = None
    temperature: float | None = None

    # Text-based summaries
    state_summary: str | None = None
    outcome_summary: str | None = None
    summary_is_computed: bool = False

    # Quantitative metrics
    return_: float = -2
    advantage: float = -2
    return_is_computed: bool = False
    advantage_is_computed: bool = False
    last_timestep: int = -1

    is_train: bool = True  # If True, use step for training
    tools: list[dict[str, Any]] | None = None
    answer: str | list[str] | None = None  # str for single-turn, list[str] for multi-turn

    # Other retrieval metadata
    system_prompt: str | None = None
    task_prompt: str | None = None
    default_context: list[dict[str, Any]] | None = None
    # Tool-calling retrieval specific
    is_retrieval: bool = False  # If True, this step is a retrieval tool call (not env step)

    # Maybe filter on complete generations
    is_complete: bool = True

    # Alternative state_action tokens to pick
    other_state_action_tokens: list[list[int]] | None = None


class Trajectory:
    """
    Sequence of EpisodeStep or StateActionSample,
    generated by a complete rollout or sourced from a dataset
    """

    def __init__(
        self,
        episode_steps: list[EpisodeStep],
        try_step: int,
        discount_factor: float,
        final_reward: float,
        last_value: float = 0.0,
    ) -> None:
        self.episode_steps = episode_steps
        self.try_step = try_step
        self.discount_factor = discount_factor
        self.final_reward = final_reward
        self.last_value = last_value

        self.returns = self.compute_returns()
        self.first_return = self.returns[0]
        self.correct = self.final_reward == 1  # heuristic for accuracy evals

        self.last_state_len = episode_steps[-1].state_len

        # Hack, but store additional episode steps associated with the trajectory
        # e.g., for PGIC samples
        self.post_rollout_episode_steps: list[EpisodeStep] = []

    def __len__(self) -> int:
        return len(self.episode_steps)

    def add_post_rollout_episode_step(
        self,
        episode_step: EpisodeStep,
    ) -> None:
        """
        Save episode
        """
        self.post_rollout_episode_steps.append(episode_step)

    def compute_returns(self) -> list[float]:
        """
        Compute returns for each episode step
        -> Also sets the last timestep for each step
        """
        if self.episode_steps[-1].return_is_computed:
            all_returns = [step.return_ for step in self.episode_steps]
            all_computed = [step.return_is_computed for step in self.episode_steps]
            not_computed_indices = [_idx for _idx, _comp in enumerate(all_computed) if not _comp]
            assert all(all_computed), (
                f"Not all returns are computed! Returns: {all_returns}\n"
                f"(Missing indices: {not_computed_indices})"
            )
            return all_returns

        # Otherwise, compute the (discounted) returns
        returns: list[float] = compute_returns_with_last_value(
            rewards=[step.reward for step in self.episode_steps],
            discount_factor=self.discount_factor,
            dones=[step.done for step in self.episode_steps],
            last_value=self.last_value,
        )
        for _idx, return_ in enumerate(returns):
            self.episode_steps[_idx].return_ = return_
            self.episode_steps[_idx].return_is_computed = True
            self.episode_steps[_idx].last_timestep = self.episode_steps[-1].timestep
        return returns


class TrajectoryGroup:
    """
    Batch of Trajectories, generated by a group of rollouts
    """

    def __init__(
        self,
        trajectories: list[Trajectory],
        discount_factor: float,
        final_rewards: list[float] | None = None,
    ) -> None:
        self.trajectories = trajectories
        self.discount_factor = discount_factor
        self.final_rewards = final_rewards or [
            trajectory.final_reward for trajectory in self.trajectories
        ]
        self.first_returns = self.get_first_returns()
        self.advantages = self.compute_advantages()

    def get_first_returns(self) -> list[float]:
        """
        Get the first returns for each trajectory, i.e.,
        the discounted sum of rewards at each step of the trajectory
        """
        # return [
        #     trajectory.compute_returns()[0] for trajectory in self.trajectories
        # ]
        return [trajectory.first_return for trajectory in self.trajectories]

    def check_advantages(self) -> list[list[float]] | None:
        """
        Check for and return already-computed advantages in the group
        """
        # Check by considering last trajectory's last step
        if self.trajectories[-1].episode_steps[-1].advantage_is_computed:
            # Now check that all steps have computed advantages
            all_advantages = [
                [step.advantage for step in trajectory.episode_steps]
                for trajectory in self.trajectories
            ]
            all_computed = [
                [step.advantage_is_computed for step in trajectory.episode_steps]
                for trajectory in self.trajectories
            ]
            for traj_idx, traj_advantages in enumerate(all_advantages):
                _not_computed_indices = [
                    _idx for _idx, _comp in enumerate(all_computed[traj_idx]) if not _comp
                ]
                assert len(_not_computed_indices) == 0, (
                    f"Not all advantages are computed for trajectory {traj_idx}!\n"
                    f"Advantages: {traj_advantages}\n(Missing indices: {_not_computed_indices})"
                )
            return all_advantages
        return None

    def compute_advantages(self) -> list[list[float]]:
        """
        Compute advantages for each episode step in the trajectory
        - By default, just use the returns as advantages
        """
        # Return advantages if they're already computed
        maybe_advantages = self.check_advantages()
        if maybe_advantages is not None:
            return maybe_advantages

        advantages = [trajectory.compute_returns() for trajectory in self.trajectories]
        for t_idx, trajectory in enumerate(self.trajectories):
            for e_idx, _ in enumerate(trajectory.episode_steps):
                self.trajectories[t_idx].episode_steps[e_idx].advantage = advantages[t_idx][e_idx]
                self.trajectories[t_idx].episode_steps[e_idx].advantage_is_computed = True
        return advantages


class MeanCenteredTrajectoryGroup(TrajectoryGroup):
    """
    Batch of Trajectories, where we compute advantages by mean-centering the final rewards, i.e.,
    advantages = final_rewards - mean(final_rewards)

    If `discount_factor` < 1, we we compute step-wise advantages by applying step-wise discounting
    *after* mean-centering the final returns (as an empirical hack to not having all MC rollouts
    per state at each timestep)
    """

    def compute_advantages(self) -> list[list[float]]:
        """
        Compute advantages for each episode step in the trajectory as (discounted) mean-centered
        final returns
        """
        # Return advantages if they're already computed
        maybe_advantages = self.check_advantages()
        if maybe_advantages is not None:
            return maybe_advantages

        # final_rewards_in_group: list[float] = [
        #     trajectory.final_reward for trajectory in self.trajectories_G
        # ]
        mean_reward: float = sum(self.final_rewards) / len(self.final_rewards)
        if self.discount_factor == 1:  # no discounting, advantage per rollout same for all steps
            return [
                [(trajectory.final_reward - mean_reward) for _ in range(len(trajectory))]
                for trajectory in self.trajectories
            ]
        # Otherwise, apply step-wise discounting after mean-centering
        advantages: list[list[float]] = [
            [
                (traj.final_reward - mean_reward) * (self.discount_factor ** (len(traj) - t - 1))
                for t in range(len(traj))
            ]
            for traj in self.trajectories
        ]
        for t_idx, trajectory in enumerate(self.trajectories):
            for e_idx, _ in enumerate(trajectory.episode_steps):
                self.trajectories[t_idx].episode_steps[e_idx].advantage = advantages[t_idx][e_idx]
                self.trajectories[t_idx].episode_steps[e_idx].advantage_is_computed = True
        return advantages
